apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
  labels:
    app: monitoring
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/subscriptionsid/resourcegroups/rageosurgroupName/providers/Microsoft.Compute/disks/Grafana-dev
