apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
  namespace: logging
  labels:
    app: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: grafana
  volumeMode: Filesystem
  volumeName: pv-grafana
  resources:
    requests:
      storage: 8Gi
